name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches: 
    - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Build the app
      uses: actions/checkout@v2
        
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Prepare and deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN}}
      run: |
        npm install
        ###
        npm run lint
        ###
        npm run test 
        ###
        npm run ng deploy -- --name="Deploy Dummy" --email="deploy@webtrix.be"
